// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightTrackerAPI.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102142324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Database.Models.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ATA")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ATD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("AirlineIata")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationIata")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ETA")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ETD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GroundSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("Heading")
                        .HasColumnType("REAL");

                    b.Property<string>("OriginIata")
                        .HasColumnType("TEXT");

                    b.Property<long?>("STA")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("STD")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
