// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightTrackerAPI.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104155155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Database.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Database.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Iata")
                        .IsUnique();

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Database.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Iata")
                        .IsUnique();

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Database.Models.Bounds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("LatitudeMax")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudeMin")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeMax")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Bounds");
                });

            modelBuilder.Entity("Database.Models.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ATA")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ATD")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Altitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Callsign")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ETA")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ETD")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GroundSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("Heading")
                        .HasColumnType("REAL");

                    b.Property<int?>("OriginId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("STA")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("STD")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightTrackerAPI.Database.Models.ActiveFlight", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("ActiveFlights");
                });

            modelBuilder.Entity("Database.Models.Flight", b =>
                {
                    b.HasOne("Database.Models.Aircraft", "Aircraft")
                        .WithMany("Flights")
                        .HasForeignKey("AircraftId");

                    b.HasOne("Database.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId");

                    b.HasOne("Database.Models.Airport", "Destination")
                        .WithMany("Arrivals")
                        .HasForeignKey("DestinationId");

                    b.HasOne("Database.Models.Airport", "Origin")
                        .WithMany("Departures")
                        .HasForeignKey("OriginId");

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("FlightTrackerAPI.Database.Models.ActiveFlight", b =>
                {
                    b.HasOne("Database.Models.Flight", "Flight")
                        .WithOne("ActiveFlight")
                        .HasForeignKey("FlightTrackerAPI.Database.Models.ActiveFlight", "FlightId");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Database.Models.Aircraft", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Database.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Database.Models.Airport", b =>
                {
                    b.Navigation("Arrivals");

                    b.Navigation("Departures");
                });

            modelBuilder.Entity("Database.Models.Flight", b =>
                {
                    b.Navigation("ActiveFlight");
                });
#pragma warning restore 612, 618
        }
    }
}
